version: '3.1'

services:
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5435:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/pgdata:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7000
    ports:
      - "7000:7000"    